Merging all the collumns (weather and river discharge data) together and merging rows of all districts together

In [1]:
import pandas as pd
import os

In [4]:
cwd = os.getcwd()
cwd

'/content'

In [70]:
file_list = os.listdir(cwd+'/Weather_data')

In [94]:
file_list

['Rajshahi_Weather_combined.csv',
 'Dhaka_Weather_combined.csv',
 'Sylhet_Weather_combined.csv',
 'Khulna_Weather_combined.csv',
 'Mymensigh_Weather_combined.csv',
 'Barisal_Weather_combined.csv',
 'Naryanganj_weather_combined.csv',
 'Comilla_Weather_combined.csv',
 'Chittagong_weather_combined.csv',
 'Bogra_Weather_combined.csv']

In [95]:
for filename in file_list:
  df_district = pd.read_csv(f'Weather_data/{filename}',index_col='datetime',parse_dates=True)
  df_district['city'] =filename.split('_')[0]
  df_district.to_csv(f'/content/{filename}')

<ipython-input-95-18640b101060>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df_district = pd.read_csv(f'Weather_data/{filename}',index_col='datetime',parse_dates=True)
<ipython-input-95-18640b101060>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df_district = pd.read_csv(f'Weather_data/{filename}',index_col='datetime',parse_dates=True)
<ipython-input-95-18640b101060>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df_district = pd.read_csv(f'Weather_data/{filename}',index_col='datetime',parse_dates=True)
<ipython-input-95-18640b101060>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df_district = pd.read_csv(f'Weather_data/{filename}',index_col='datetime',parse_dates=True)
<ipython-input-95-18640b101060>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df_district = pd.read_csv(f'Weather_data/{filename}',index_col='datetime',parse_dates=True)
<ipython-input-95-18640b101060>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df_district = pd.read_csv(f'Weather_data/{filename}',index_col='datetime',parse_dates=True)

In [96]:
df = pd.concat( map(pd.read_csv, ['Rajshahi_Weather_combined.csv',
 'Dhaka_Weather_combined.csv',
 'Sylhet_Weather_combined.csv',
 'Khulna_Weather_combined.csv',
 'Mymensigh_Weather_combined.csv',
 'Barisal_Weather_combined.csv',
 'Naryanganj_weather_combined.csv',
 'Comilla_Weather_combined.csv',
 'Chittagong_weather_combined.csv',
 'Bogra_Weather_combined.csv']), ignore_index=True)

In [97]:
df.to_csv('Weather_allCities.csv', index=False)

In [98]:
df.head(5)

,datetime,Unnamed: 0_x,name,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,...,windspeed_x,weathercode,tempmax_y,tempmin_y,feelslikemax_y,feelslikemin_y,precipitation_sum,rain_sum,windspeed_y,precipitation_hours
0,2012-01-01,0.0,Rajshahi,80.1,58.4,67.9,79.8,58.4,67.9,54.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2012-02-01,1.0,Rajshahi,73.7,61.2,65.2,73.7,61.2,65.2,57.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2012-03-01,2.0,Rajshahi,77.3,58.6,66.2,77.3,58.6,66.2,57.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2012-04-01,3.0,Rajshahi,77.8,55.5,66.0,77.8,55.5,66.0,55.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2012-05-01,4.0,Rajshahi,79.1,53.0,67.0,79.1,53.0,67.0,56.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN